---
params: 
    title: ""
    Pars: "`r list()`"
    plotPars: "`r list()`"
    tabs: "`r TRUE`"
    its: " `r numeric()`"
    nyears: " `r numeric()`"
    proyears: " `r numeric()`"
    date: "`r Sys.Date()`"
title: "`r params$title`"
date: "`r params$date`"
output:
  html_document
---



## Interpreting results of Management Performance 


### Posterior versus observed data

When an MP was tested using closed-loop simulation, for every simulation, in every year of the projection simulated data were generated. These multiple simulated data sets provides a basis for comparison with a single observed data from the real fishery system whilst an MP was in use. 

Since an MP is codified, the only explanations for the observation of data that differ from those of the simulation is that either the operating model is misspecfied (either historically and/or in the future) or the operating model is correct and by chance atypical data have been collected. 


```{r MPerf_Chunk1, echo=F,warning=F,error=F,message=F,results='asis',fig.width=10,fig.height=10}

 
  post_marg_plot(MSEobj_Eval,dat,dat_ind)

  FigInd<-FigInd+1

```

Figure `r paste(SecInd,FigInd,sep=".")`. Posterior predicted data (48 simulations) for catch, mean length and a relative abundance index for the base operating model over the first 5 years of a projection (shaded regions) compared with observed (points) data over the same time period during which the DCAC MP was in use. 
